image: "python:3.7"

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - python --version
  - pip install pipenv
  - pipenv install --system --deploy --ignore-pipfile --dev

stages:
  - test

flake8:
  stage: test
  script:
  - flake8

pytest:
  stage: test
  script:
  - pytest tests/
