image: "python:3.7"

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - python --version
  - pipenv install --system --deploy --ignore-pipfile --dev

stages:
  - Static Analysis

flake8:
  stage: Static Analysis
  script:
  - flake8 app/