image: "python:3.7"

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - python --version
  - pip install pipenv
  - pipenv install --system --deploy --ignore-pipfile --dev

stages:
  - Static Analysis
  - Test

flake8:
  stage: Static Analysis
  script:
  - flake8 app/

pytest:
  stage: Test
  script:
  - pytest tests/
